// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/xmlservice.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDocumentRequest) Reset() {
	*x = GetDocumentRequest{}
	mi := &file_proto_xmlservice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDocumentRequest) ProtoMessage() {}

func (x *GetDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_xmlservice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDocumentRequest.ProtoReflect.Descriptor instead.
func (*GetDocumentRequest) Descriptor() ([]byte, []int) {
	return file_proto_xmlservice_proto_rawDescGZIP(), []int{0}
}

func (x *GetDocumentRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetDocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XmlDocument   string                 `protobuf:"bytes,2,opt,name=xml_document,json=xmlDocument,proto3" json:"xml_document,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	MapperVersion string                 `protobuf:"bytes,4,opt,name=mapper_version,json=mapperVersion,proto3" json:"mapper_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDocumentResponse) Reset() {
	*x = GetDocumentResponse{}
	mi := &file_proto_xmlservice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDocumentResponse) ProtoMessage() {}

func (x *GetDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_xmlservice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDocumentResponse.ProtoReflect.Descriptor instead.
func (*GetDocumentResponse) Descriptor() ([]byte, []int) {
	return file_proto_xmlservice_proto_rawDescGZIP(), []int{1}
}

func (x *GetDocumentResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetDocumentResponse) GetXmlDocument() string {
	if x != nil {
		return x.XmlDocument
	}
	return ""
}

func (x *GetDocumentResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *GetDocumentResponse) GetMapperVersion() string {
	if x != nil {
		return x.MapperVersion
	}
	return ""
}

type QueryParkStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	FromDate      string                 `protobuf:"bytes,2,opt,name=from_date,json=fromDate,proto3" json:"from_date,omitempty"`
	ToDate        string                 `protobuf:"bytes,3,opt,name=to_date,json=toDate,proto3" json:"to_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryParkStatsRequest) Reset() {
	*x = QueryParkStatsRequest{}
	mi := &file_proto_xmlservice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryParkStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryParkStatsRequest) ProtoMessage() {}

func (x *QueryParkStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_xmlservice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryParkStatsRequest.ProtoReflect.Descriptor instead.
func (*QueryParkStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_xmlservice_proto_rawDescGZIP(), []int{2}
}

func (x *QueryParkStatsRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *QueryParkStatsRequest) GetFromDate() string {
	if x != nil {
		return x.FromDate
	}
	return ""
}

func (x *QueryParkStatsRequest) GetToDate() string {
	if x != nil {
		return x.ToDate
	}
	return ""
}

type QueryParkStatsResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	State                 string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	ParkCount             int64                  `protobuf:"varint,2,opt,name=park_count,json=parkCount,proto3" json:"park_count,omitempty"`
	AvgTempMeanC          float64                `protobuf:"fixed64,3,opt,name=avg_temp_mean_c,json=avgTempMeanC,proto3" json:"avg_temp_mean_c,omitempty"`
	AvgPrecipitationValue float64                `protobuf:"fixed64,4,opt,name=avg_precipitation_value,json=avgPrecipitationValue,proto3" json:"avg_precipitation_value,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *QueryParkStatsResponse) Reset() {
	*x = QueryParkStatsResponse{}
	mi := &file_proto_xmlservice_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryParkStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryParkStatsResponse) ProtoMessage() {}

func (x *QueryParkStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_xmlservice_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryParkStatsResponse.ProtoReflect.Descriptor instead.
func (*QueryParkStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_xmlservice_proto_rawDescGZIP(), []int{3}
}

func (x *QueryParkStatsResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *QueryParkStatsResponse) GetParkCount() int64 {
	if x != nil {
		return x.ParkCount
	}
	return 0
}

func (x *QueryParkStatsResponse) GetAvgTempMeanC() float64 {
	if x != nil {
		return x.AvgTempMeanC
	}
	return 0
}

func (x *QueryParkStatsResponse) GetAvgPrecipitationValue() float64 {
	if x != nil {
		return x.AvgPrecipitationValue
	}
	return 0
}

type QueryTopParksByTempRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	FromDate      string                 `protobuf:"bytes,2,opt,name=from_date,json=fromDate,proto3" json:"from_date,omitempty"`
	ToDate        string                 `protobuf:"bytes,3,opt,name=to_date,json=toDate,proto3" json:"to_date,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryTopParksByTempRequest) Reset() {
	*x = QueryTopParksByTempRequest{}
	mi := &file_proto_xmlservice_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryTopParksByTempRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTopParksByTempRequest) ProtoMessage() {}

func (x *QueryTopParksByTempRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_xmlservice_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTopParksByTempRequest.ProtoReflect.Descriptor instead.
func (*QueryTopParksByTempRequest) Descriptor() ([]byte, []int) {
	return file_proto_xmlservice_proto_rawDescGZIP(), []int{4}
}

func (x *QueryTopParksByTempRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *QueryTopParksByTempRequest) GetFromDate() string {
	if x != nil {
		return x.FromDate
	}
	return ""
}

func (x *QueryTopParksByTempRequest) GetToDate() string {
	if x != nil {
		return x.ToDate
	}
	return ""
}

func (x *QueryTopParksByTempRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ParkTemperatureRank struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ParkCode              string                 `protobuf:"bytes,1,opt,name=park_code,json=parkCode,proto3" json:"park_code,omitempty"`
	ParkName              string                 `protobuf:"bytes,2,opt,name=park_name,json=parkName,proto3" json:"park_name,omitempty"`
	AvgTempMeanC          float64                `protobuf:"fixed64,3,opt,name=avg_temp_mean_c,json=avgTempMeanC,proto3" json:"avg_temp_mean_c,omitempty"`
	AvgPrecipitationValue float64                `protobuf:"fixed64,4,opt,name=avg_precipitation_value,json=avgPrecipitationValue,proto3" json:"avg_precipitation_value,omitempty"`
	ObservationCount      int32                  `protobuf:"varint,5,opt,name=observation_count,json=observationCount,proto3" json:"observation_count,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ParkTemperatureRank) Reset() {
	*x = ParkTemperatureRank{}
	mi := &file_proto_xmlservice_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParkTemperatureRank) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParkTemperatureRank) ProtoMessage() {}

func (x *ParkTemperatureRank) ProtoReflect() protoreflect.Message {
	mi := &file_proto_xmlservice_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParkTemperatureRank.ProtoReflect.Descriptor instead.
func (*ParkTemperatureRank) Descriptor() ([]byte, []int) {
	return file_proto_xmlservice_proto_rawDescGZIP(), []int{5}
}

func (x *ParkTemperatureRank) GetParkCode() string {
	if x != nil {
		return x.ParkCode
	}
	return ""
}

func (x *ParkTemperatureRank) GetParkName() string {
	if x != nil {
		return x.ParkName
	}
	return ""
}

func (x *ParkTemperatureRank) GetAvgTempMeanC() float64 {
	if x != nil {
		return x.AvgTempMeanC
	}
	return 0
}

func (x *ParkTemperatureRank) GetAvgPrecipitationValue() float64 {
	if x != nil {
		return x.AvgPrecipitationValue
	}
	return 0
}

func (x *ParkTemperatureRank) GetObservationCount() int32 {
	if x != nil {
		return x.ObservationCount
	}
	return 0
}

type QueryTopParksByTempResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ParkTemperatureRank `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryTopParksByTempResponse) Reset() {
	*x = QueryTopParksByTempResponse{}
	mi := &file_proto_xmlservice_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryTopParksByTempResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTopParksByTempResponse) ProtoMessage() {}

func (x *QueryTopParksByTempResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_xmlservice_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTopParksByTempResponse.ProtoReflect.Descriptor instead.
func (*QueryTopParksByTempResponse) Descriptor() ([]byte, []int) {
	return file_proto_xmlservice_proto_rawDescGZIP(), []int{6}
}

func (x *QueryTopParksByTempResponse) GetItems() []*ParkTemperatureRank {
	if x != nil {
		return x.Items
	}
	return nil
}

type QueryDailyStateSummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	FromDate      string                 `protobuf:"bytes,2,opt,name=from_date,json=fromDate,proto3" json:"from_date,omitempty"`
	ToDate        string                 `protobuf:"bytes,3,opt,name=to_date,json=toDate,proto3" json:"to_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryDailyStateSummaryRequest) Reset() {
	*x = QueryDailyStateSummaryRequest{}
	mi := &file_proto_xmlservice_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryDailyStateSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryDailyStateSummaryRequest) ProtoMessage() {}

func (x *QueryDailyStateSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_xmlservice_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryDailyStateSummaryRequest.ProtoReflect.Descriptor instead.
func (*QueryDailyStateSummaryRequest) Descriptor() ([]byte, []int) {
	return file_proto_xmlservice_proto_rawDescGZIP(), []int{7}
}

func (x *QueryDailyStateSummaryRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *QueryDailyStateSummaryRequest) GetFromDate() string {
	if x != nil {
		return x.FromDate
	}
	return ""
}

func (x *QueryDailyStateSummaryRequest) GetToDate() string {
	if x != nil {
		return x.ToDate
	}
	return ""
}

type DailyStateSummary struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Date                  string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	ParkCount             int32                  `protobuf:"varint,2,opt,name=park_count,json=parkCount,proto3" json:"park_count,omitempty"`
	AvgTempMeanC          float64                `protobuf:"fixed64,3,opt,name=avg_temp_mean_c,json=avgTempMeanC,proto3" json:"avg_temp_mean_c,omitempty"`
	AvgPrecipitationValue float64                `protobuf:"fixed64,4,opt,name=avg_precipitation_value,json=avgPrecipitationValue,proto3" json:"avg_precipitation_value,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *DailyStateSummary) Reset() {
	*x = DailyStateSummary{}
	mi := &file_proto_xmlservice_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DailyStateSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyStateSummary) ProtoMessage() {}

func (x *DailyStateSummary) ProtoReflect() protoreflect.Message {
	mi := &file_proto_xmlservice_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailyStateSummary.ProtoReflect.Descriptor instead.
func (*DailyStateSummary) Descriptor() ([]byte, []int) {
	return file_proto_xmlservice_proto_rawDescGZIP(), []int{8}
}

func (x *DailyStateSummary) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *DailyStateSummary) GetParkCount() int32 {
	if x != nil {
		return x.ParkCount
	}
	return 0
}

func (x *DailyStateSummary) GetAvgTempMeanC() float64 {
	if x != nil {
		return x.AvgTempMeanC
	}
	return 0
}

func (x *DailyStateSummary) GetAvgPrecipitationValue() float64 {
	if x != nil {
		return x.AvgPrecipitationValue
	}
	return 0
}

type QueryDailyStateSummaryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*DailyStateSummary   `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryDailyStateSummaryResponse) Reset() {
	*x = QueryDailyStateSummaryResponse{}
	mi := &file_proto_xmlservice_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryDailyStateSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryDailyStateSummaryResponse) ProtoMessage() {}

func (x *QueryDailyStateSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_xmlservice_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryDailyStateSummaryResponse.ProtoReflect.Descriptor instead.
func (*QueryDailyStateSummaryResponse) Descriptor() ([]byte, []int) {
	return file_proto_xmlservice_proto_rawDescGZIP(), []int{9}
}

func (x *QueryDailyStateSummaryResponse) GetItems() []*DailyStateSummary {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_proto_xmlservice_proto protoreflect.FileDescriptor

const file_proto_xmlservice_proto_rawDesc = "" +
	"\n" +
	"\x16proto/xmlservice.proto\x12\n" +
	"xmlservice\"$\n" +
	"\x12GetDocumentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x8e\x01\n" +
	"\x13GetDocumentResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12!\n" +
	"\fxml_document\x18\x02 \x01(\tR\vxmlDocument\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\tR\tcreatedAt\x12%\n" +
	"\x0emapper_version\x18\x04 \x01(\tR\rmapperVersion\"c\n" +
	"\x15QueryParkStatsRequest\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\x12\x1b\n" +
	"\tfrom_date\x18\x02 \x01(\tR\bfromDate\x12\x17\n" +
	"\ato_date\x18\x03 \x01(\tR\x06toDate\"\xac\x01\n" +
	"\x16QueryParkStatsResponse\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\x12\x1d\n" +
	"\n" +
	"park_count\x18\x02 \x01(\x03R\tparkCount\x12%\n" +
	"\x0favg_temp_mean_c\x18\x03 \x01(\x01R\favgTempMeanC\x126\n" +
	"\x17avg_precipitation_value\x18\x04 \x01(\x01R\x15avgPrecipitationValue\"~\n" +
	"\x1aQueryTopParksByTempRequest\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\x12\x1b\n" +
	"\tfrom_date\x18\x02 \x01(\tR\bfromDate\x12\x17\n" +
	"\ato_date\x18\x03 \x01(\tR\x06toDate\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"\xdb\x01\n" +
	"\x13ParkTemperatureRank\x12\x1b\n" +
	"\tpark_code\x18\x01 \x01(\tR\bparkCode\x12\x1b\n" +
	"\tpark_name\x18\x02 \x01(\tR\bparkName\x12%\n" +
	"\x0favg_temp_mean_c\x18\x03 \x01(\x01R\favgTempMeanC\x126\n" +
	"\x17avg_precipitation_value\x18\x04 \x01(\x01R\x15avgPrecipitationValue\x12+\n" +
	"\x11observation_count\x18\x05 \x01(\x05R\x10observationCount\"T\n" +
	"\x1bQueryTopParksByTempResponse\x125\n" +
	"\x05items\x18\x01 \x03(\v2\x1f.xmlservice.ParkTemperatureRankR\x05items\"k\n" +
	"\x1dQueryDailyStateSummaryRequest\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\x12\x1b\n" +
	"\tfrom_date\x18\x02 \x01(\tR\bfromDate\x12\x17\n" +
	"\ato_date\x18\x03 \x01(\tR\x06toDate\"\xa5\x01\n" +
	"\x11DailyStateSummary\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x1d\n" +
	"\n" +
	"park_count\x18\x02 \x01(\x05R\tparkCount\x12%\n" +
	"\x0favg_temp_mean_c\x18\x03 \x01(\x01R\favgTempMeanC\x126\n" +
	"\x17avg_precipitation_value\x18\x04 \x01(\x01R\x15avgPrecipitationValue\"U\n" +
	"\x1eQueryDailyStateSummaryResponse\x123\n" +
	"\x05items\x18\x01 \x03(\v2\x1d.xmlservice.DailyStateSummaryR\x05items2\x8e\x03\n" +
	"\n" +
	"XmlService\x12N\n" +
	"\vGetDocument\x12\x1e.xmlservice.GetDocumentRequest\x1a\x1f.xmlservice.GetDocumentResponse\x12W\n" +
	"\x0eQueryParkStats\x12!.xmlservice.QueryParkStatsRequest\x1a\".xmlservice.QueryParkStatsResponse\x12f\n" +
	"\x13QueryTopParksByTemp\x12&.xmlservice.QueryTopParksByTempRequest\x1a'.xmlservice.QueryTopParksByTempResponse\x12o\n" +
	"\x16QueryDailyStateSummary\x12).xmlservice.QueryDailyStateSummaryRequest\x1a*.xmlservice.QueryDailyStateSummaryResponseB\x19Z\x17xml-service/proto;protob\x06proto3"

var (
	file_proto_xmlservice_proto_rawDescOnce sync.Once
	file_proto_xmlservice_proto_rawDescData []byte
)

func file_proto_xmlservice_proto_rawDescGZIP() []byte {
	file_proto_xmlservice_proto_rawDescOnce.Do(func() {
		file_proto_xmlservice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_xmlservice_proto_rawDesc), len(file_proto_xmlservice_proto_rawDesc)))
	})
	return file_proto_xmlservice_proto_rawDescData
}

var file_proto_xmlservice_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_xmlservice_proto_goTypes = []any{
	(*GetDocumentRequest)(nil),             // 0: xmlservice.GetDocumentRequest
	(*GetDocumentResponse)(nil),            // 1: xmlservice.GetDocumentResponse
	(*QueryParkStatsRequest)(nil),          // 2: xmlservice.QueryParkStatsRequest
	(*QueryParkStatsResponse)(nil),         // 3: xmlservice.QueryParkStatsResponse
	(*QueryTopParksByTempRequest)(nil),     // 4: xmlservice.QueryTopParksByTempRequest
	(*ParkTemperatureRank)(nil),            // 5: xmlservice.ParkTemperatureRank
	(*QueryTopParksByTempResponse)(nil),    // 6: xmlservice.QueryTopParksByTempResponse
	(*QueryDailyStateSummaryRequest)(nil),  // 7: xmlservice.QueryDailyStateSummaryRequest
	(*DailyStateSummary)(nil),              // 8: xmlservice.DailyStateSummary
	(*QueryDailyStateSummaryResponse)(nil), // 9: xmlservice.QueryDailyStateSummaryResponse
}
var file_proto_xmlservice_proto_depIdxs = []int32{
	5, // 0: xmlservice.QueryTopParksByTempResponse.items:type_name -> xmlservice.ParkTemperatureRank
	8, // 1: xmlservice.QueryDailyStateSummaryResponse.items:type_name -> xmlservice.DailyStateSummary
	0, // 2: xmlservice.XmlService.GetDocument:input_type -> xmlservice.GetDocumentRequest
	2, // 3: xmlservice.XmlService.QueryParkStats:input_type -> xmlservice.QueryParkStatsRequest
	4, // 4: xmlservice.XmlService.QueryTopParksByTemp:input_type -> xmlservice.QueryTopParksByTempRequest
	7, // 5: xmlservice.XmlService.QueryDailyStateSummary:input_type -> xmlservice.QueryDailyStateSummaryRequest
	1, // 6: xmlservice.XmlService.GetDocument:output_type -> xmlservice.GetDocumentResponse
	3, // 7: xmlservice.XmlService.QueryParkStats:output_type -> xmlservice.QueryParkStatsResponse
	6, // 8: xmlservice.XmlService.QueryTopParksByTemp:output_type -> xmlservice.QueryTopParksByTempResponse
	9, // 9: xmlservice.XmlService.QueryDailyStateSummary:output_type -> xmlservice.QueryDailyStateSummaryResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_xmlservice_proto_init() }
func file_proto_xmlservice_proto_init() {
	if File_proto_xmlservice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_xmlservice_proto_rawDesc), len(file_proto_xmlservice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_xmlservice_proto_goTypes,
		DependencyIndexes: file_proto_xmlservice_proto_depIdxs,
		MessageInfos:      file_proto_xmlservice_proto_msgTypes,
	}.Build()
	File_proto_xmlservice_proto = out.File
	file_proto_xmlservice_proto_goTypes = nil
	file_proto_xmlservice_proto_depIdxs = nil
}
