// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v3.21.12
// source: proto/xmlservice.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetDocumentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetDocumentRequest) Reset() {
	*x = GetDocumentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_xmlservice_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDocumentRequest) ProtoMessage() {}

func (x *GetDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_xmlservice_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDocumentRequest.ProtoReflect.Descriptor instead.
func (*GetDocumentRequest) Descriptor() ([]byte, []int) {
	return file_proto_xmlservice_proto_rawDescGZIP(), []int{0}
}

func (x *GetDocumentRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetDocumentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XmlDocument   string `protobuf:"bytes,2,opt,name=xml_document,json=xmlDocument,proto3" json:"xml_document,omitempty"`
	CreatedAt     string `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	MapperVersion string `protobuf:"bytes,4,opt,name=mapper_version,json=mapperVersion,proto3" json:"mapper_version,omitempty"`
}

func (x *GetDocumentResponse) Reset() {
	*x = GetDocumentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_xmlservice_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDocumentResponse) ProtoMessage() {}

func (x *GetDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_xmlservice_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDocumentResponse.ProtoReflect.Descriptor instead.
func (*GetDocumentResponse) Descriptor() ([]byte, []int) {
	return file_proto_xmlservice_proto_rawDescGZIP(), []int{1}
}

func (x *GetDocumentResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetDocumentResponse) GetXmlDocument() string {
	if x != nil {
		return x.XmlDocument
	}
	return ""
}

func (x *GetDocumentResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *GetDocumentResponse) GetMapperVersion() string {
	if x != nil {
		return x.MapperVersion
	}
	return ""
}

type QueryCurrentPriceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sku string `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
}

func (x *QueryCurrentPriceRequest) Reset() {
	*x = QueryCurrentPriceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_xmlservice_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryCurrentPriceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryCurrentPriceRequest) ProtoMessage() {}

func (x *QueryCurrentPriceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_xmlservice_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryCurrentPriceRequest.ProtoReflect.Descriptor instead.
func (*QueryCurrentPriceRequest) Descriptor() ([]byte, []int) {
	return file_proto_xmlservice_proto_rawDescGZIP(), []int{2}
}

func (x *QueryCurrentPriceRequest) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

type QueryCurrentPriceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sku        string  `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	PrecoAtual float64 `protobuf:"fixed64,2,opt,name=preco_atual,json=precoAtual,proto3" json:"preco_atual,omitempty"`
}

func (x *QueryCurrentPriceResponse) Reset() {
	*x = QueryCurrentPriceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_xmlservice_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryCurrentPriceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryCurrentPriceResponse) ProtoMessage() {}

func (x *QueryCurrentPriceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_xmlservice_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryCurrentPriceResponse.ProtoReflect.Descriptor instead.
func (*QueryCurrentPriceResponse) Descriptor() ([]byte, []int) {
	return file_proto_xmlservice_proto_rawDescGZIP(), []int{3}
}

func (x *QueryCurrentPriceResponse) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *QueryCurrentPriceResponse) GetPrecoAtual() float64 {
	if x != nil {
		return x.PrecoAtual
	}
	return 0
}

type QueryIncidentStatsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Borough  string `protobuf:"bytes,1,opt,name=borough,proto3" json:"borough,omitempty"`
	FromDate string `protobuf:"bytes,2,opt,name=from_date,json=fromDate,proto3" json:"from_date,omitempty"`
	ToDate   string `protobuf:"bytes,3,opt,name=to_date,json=toDate,proto3" json:"to_date,omitempty"`
}

func (x *QueryIncidentStatsRequest) Reset() {
	*x = QueryIncidentStatsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_xmlservice_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryIncidentStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryIncidentStatsRequest) ProtoMessage() {}

func (x *QueryIncidentStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_xmlservice_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryIncidentStatsRequest.ProtoReflect.Descriptor instead.
func (*QueryIncidentStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_xmlservice_proto_rawDescGZIP(), []int{4}
}

func (x *QueryIncidentStatsRequest) GetBorough() string {
	if x != nil {
		return x.Borough
	}
	return ""
}

func (x *QueryIncidentStatsRequest) GetFromDate() string {
	if x != nil {
		return x.FromDate
	}
	return ""
}

func (x *QueryIncidentStatsRequest) GetToDate() string {
	if x != nil {
		return x.ToDate
	}
	return ""
}

type QueryIncidentStatsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Borough            string  `protobuf:"bytes,1,opt,name=borough,proto3" json:"borough,omitempty"`
	IncidentCount      int64   `protobuf:"varint,2,opt,name=incident_count,json=incidentCount,proto3" json:"incident_count,omitempty"`
	AvgInspections_30D float64 `protobuf:"fixed64,3,opt,name=avg_inspections_30d,json=avgInspections30d,proto3" json:"avg_inspections_30d,omitempty"`
	AvgNotApprovedRate float64 `protobuf:"fixed64,4,opt,name=avg_not_approved_rate,json=avgNotApprovedRate,proto3" json:"avg_not_approved_rate,omitempty"`
}

func (x *QueryIncidentStatsResponse) Reset() {
	*x = QueryIncidentStatsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_xmlservice_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryIncidentStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryIncidentStatsResponse) ProtoMessage() {}

func (x *QueryIncidentStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_xmlservice_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryIncidentStatsResponse.ProtoReflect.Descriptor instead.
func (*QueryIncidentStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_xmlservice_proto_rawDescGZIP(), []int{5}
}

func (x *QueryIncidentStatsResponse) GetBorough() string {
	if x != nil {
		return x.Borough
	}
	return ""
}

func (x *QueryIncidentStatsResponse) GetIncidentCount() int64 {
	if x != nil {
		return x.IncidentCount
	}
	return 0
}

func (x *QueryIncidentStatsResponse) GetAvgInspections_30D() float64 {
	if x != nil {
		return x.AvgInspections_30D
	}
	return 0
}

func (x *QueryIncidentStatsResponse) GetAvgNotApprovedRate() float64 {
	if x != nil {
		return x.AvgNotApprovedRate
	}
	return 0
}

var File_proto_xmlservice_proto protoreflect.FileDescriptor

var file_proto_xmlservice_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x78, 0x6d, 0x6c, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x78, 0x6d, 0x6c, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x22, 0x24, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x44, 0x6f, 0x63, 0x75, 0x6d,
	0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x8e, 0x01, 0x0a, 0x13, 0x47,
	0x65, 0x74, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x78, 0x6d, 0x6c, 0x5f, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65,
	0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x78, 0x6d, 0x6c, 0x44, 0x6f, 0x63,
	0x75, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x5f, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x41, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x6d, 0x61, 0x70, 0x70, 0x65, 0x72, 0x5f, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x6d, 0x61,
	0x70, 0x70, 0x65, 0x72, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x2c, 0x0a, 0x18, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x50, 0x72, 0x69, 0x63, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x6b, 0x75, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x6b, 0x75, 0x22, 0x4e, 0x0a, 0x19, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x50, 0x72, 0x69, 0x63, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x6b, 0x75, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x6b, 0x75, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x72, 0x65, 0x63,
	0x6f, 0x5f, 0x61, 0x74, 0x75, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0a, 0x70,
	0x72, 0x65, 0x63, 0x6f, 0x41, 0x74, 0x75, 0x61, 0x6c, 0x22, 0x6b, 0x0a, 0x19, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x49, 0x6e, 0x63, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x6f, 0x72, 0x6f, 0x75, 0x67,
	0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x62, 0x6f, 0x72, 0x6f, 0x75, 0x67, 0x68,
	0x12, 0x1b, 0x0a, 0x09, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x72, 0x6f, 0x6d, 0x44, 0x61, 0x74, 0x65, 0x12, 0x17, 0x0a,
	0x07, 0x74, 0x6f, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x74, 0x6f, 0x44, 0x61, 0x74, 0x65, 0x22, 0xc0, 0x01, 0x0a, 0x1a, 0x51, 0x75, 0x65, 0x72, 0x79,
	0x49, 0x6e, 0x63, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x6f, 0x72, 0x6f, 0x75, 0x67, 0x68,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x62, 0x6f, 0x72, 0x6f, 0x75, 0x67, 0x68, 0x12,
	0x25, 0x0a, 0x0e, 0x69, 0x6e, 0x63, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x5f, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x69, 0x6e, 0x63, 0x69, 0x64, 0x65, 0x6e,
	0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x2e, 0x0a, 0x13, 0x61, 0x76, 0x67, 0x5f, 0x69, 0x6e,
	0x73, 0x70, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x5f, 0x33, 0x30, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x11, 0x61, 0x76, 0x67, 0x49, 0x6e, 0x73, 0x70, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x33, 0x30, 0x64, 0x12, 0x31, 0x0a, 0x15, 0x61, 0x76, 0x67, 0x5f, 0x6e, 0x6f,
	0x74, 0x5f, 0x61, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x64, 0x5f, 0x72, 0x61, 0x74, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x12, 0x61, 0x76, 0x67, 0x4e, 0x6f, 0x74, 0x41, 0x70, 0x70,
	0x72, 0x6f, 0x76, 0x65, 0x64, 0x52, 0x61, 0x74, 0x65, 0x32, 0xa3, 0x02, 0x0a, 0x0a, 0x58, 0x6d,
	0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4e, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x44,
	0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x1e, 0x2e, 0x78, 0x6d, 0x6c, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x78, 0x6d, 0x6c, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x60, 0x0a, 0x11, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x24, 0x2e,
	0x78, 0x6d, 0x6c, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79,
	0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x50, 0x72, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x78, 0x6d, 0x6c, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x50, 0x72, 0x69,
	0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x63, 0x0a, 0x12, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x49, 0x6e, 0x63, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x73,
	0x12, 0x25, 0x2e, 0x78, 0x6d, 0x6c, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x49, 0x6e, 0x63, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x78, 0x6d, 0x6c, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x49, 0x6e, 0x63, 0x69, 0x64, 0x65,
	0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x19, 0x5a, 0x17, 0x78, 0x6d, 0x6c, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_proto_xmlservice_proto_rawDescOnce sync.Once
	file_proto_xmlservice_proto_rawDescData = file_proto_xmlservice_proto_rawDesc
)

func file_proto_xmlservice_proto_rawDescGZIP() []byte {
	file_proto_xmlservice_proto_rawDescOnce.Do(func() {
		file_proto_xmlservice_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_xmlservice_proto_rawDescData)
	})
	return file_proto_xmlservice_proto_rawDescData
}

var file_proto_xmlservice_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_xmlservice_proto_goTypes = []interface{}{
	(*GetDocumentRequest)(nil),         // 0: xmlservice.GetDocumentRequest
	(*GetDocumentResponse)(nil),        // 1: xmlservice.GetDocumentResponse
	(*QueryCurrentPriceRequest)(nil),   // 2: xmlservice.QueryCurrentPriceRequest
	(*QueryCurrentPriceResponse)(nil),  // 3: xmlservice.QueryCurrentPriceResponse
	(*QueryIncidentStatsRequest)(nil),  // 4: xmlservice.QueryIncidentStatsRequest
	(*QueryIncidentStatsResponse)(nil), // 5: xmlservice.QueryIncidentStatsResponse
}
var file_proto_xmlservice_proto_depIdxs = []int32{
	0, // 0: xmlservice.XmlService.GetDocument:input_type -> xmlservice.GetDocumentRequest
	2, // 1: xmlservice.XmlService.QueryCurrentPrice:input_type -> xmlservice.QueryCurrentPriceRequest
	4, // 2: xmlservice.XmlService.QueryIncidentStats:input_type -> xmlservice.QueryIncidentStatsRequest
	1, // 3: xmlservice.XmlService.GetDocument:output_type -> xmlservice.GetDocumentResponse
	3, // 4: xmlservice.XmlService.QueryCurrentPrice:output_type -> xmlservice.QueryCurrentPriceResponse
	5, // 5: xmlservice.XmlService.QueryIncidentStats:output_type -> xmlservice.QueryIncidentStatsResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_xmlservice_proto_init() }
func file_proto_xmlservice_proto_init() {
	if File_proto_xmlservice_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_xmlservice_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDocumentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_xmlservice_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDocumentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_xmlservice_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryCurrentPriceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_xmlservice_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryCurrentPriceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_xmlservice_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryIncidentStatsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_xmlservice_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryIncidentStatsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_xmlservice_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_xmlservice_proto_goTypes,
		DependencyIndexes: file_proto_xmlservice_proto_depIdxs,
		MessageInfos:      file_proto_xmlservice_proto_msgTypes,
	}.Build()
	File_proto_xmlservice_proto = out.File
	file_proto_xmlservice_proto_rawDesc = nil
	file_proto_xmlservice_proto_goTypes = nil
	file_proto_xmlservice_proto_depIdxs = nil
}
