// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: proto/xmlservice.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	XmlService_GetDocument_FullMethodName            = "/xmlservice.XmlService/GetDocument"
	XmlService_QueryParkStats_FullMethodName         = "/xmlservice.XmlService/QueryParkStats"
	XmlService_QueryTopParksByTemp_FullMethodName    = "/xmlservice.XmlService/QueryTopParksByTemp"
	XmlService_QueryDailyStateSummary_FullMethodName = "/xmlservice.XmlService/QueryDailyStateSummary"
)

// XmlServiceClient is the client API for XmlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type XmlServiceClient interface {
	GetDocument(ctx context.Context, in *GetDocumentRequest, opts ...grpc.CallOption) (*GetDocumentResponse, error)
	QueryParkStats(ctx context.Context, in *QueryParkStatsRequest, opts ...grpc.CallOption) (*QueryParkStatsResponse, error)
	QueryTopParksByTemp(ctx context.Context, in *QueryTopParksByTempRequest, opts ...grpc.CallOption) (*QueryTopParksByTempResponse, error)
	QueryDailyStateSummary(ctx context.Context, in *QueryDailyStateSummaryRequest, opts ...grpc.CallOption) (*QueryDailyStateSummaryResponse, error)
}

type xmlServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewXmlServiceClient(cc grpc.ClientConnInterface) XmlServiceClient {
	return &xmlServiceClient{cc}
}

func (c *xmlServiceClient) GetDocument(ctx context.Context, in *GetDocumentRequest, opts ...grpc.CallOption) (*GetDocumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDocumentResponse)
	err := c.cc.Invoke(ctx, XmlService_GetDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xmlServiceClient) QueryParkStats(ctx context.Context, in *QueryParkStatsRequest, opts ...grpc.CallOption) (*QueryParkStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryParkStatsResponse)
	err := c.cc.Invoke(ctx, XmlService_QueryParkStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xmlServiceClient) QueryTopParksByTemp(ctx context.Context, in *QueryTopParksByTempRequest, opts ...grpc.CallOption) (*QueryTopParksByTempResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryTopParksByTempResponse)
	err := c.cc.Invoke(ctx, XmlService_QueryTopParksByTemp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xmlServiceClient) QueryDailyStateSummary(ctx context.Context, in *QueryDailyStateSummaryRequest, opts ...grpc.CallOption) (*QueryDailyStateSummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryDailyStateSummaryResponse)
	err := c.cc.Invoke(ctx, XmlService_QueryDailyStateSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// XmlServiceServer is the server API for XmlService service.
// All implementations must embed UnimplementedXmlServiceServer
// for forward compatibility.
type XmlServiceServer interface {
	GetDocument(context.Context, *GetDocumentRequest) (*GetDocumentResponse, error)
	QueryParkStats(context.Context, *QueryParkStatsRequest) (*QueryParkStatsResponse, error)
	QueryTopParksByTemp(context.Context, *QueryTopParksByTempRequest) (*QueryTopParksByTempResponse, error)
	QueryDailyStateSummary(context.Context, *QueryDailyStateSummaryRequest) (*QueryDailyStateSummaryResponse, error)
	mustEmbedUnimplementedXmlServiceServer()
}

// UnimplementedXmlServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedXmlServiceServer struct{}

func (UnimplementedXmlServiceServer) GetDocument(context.Context, *GetDocumentRequest) (*GetDocumentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDocument not implemented")
}
func (UnimplementedXmlServiceServer) QueryParkStats(context.Context, *QueryParkStatsRequest) (*QueryParkStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryParkStats not implemented")
}
func (UnimplementedXmlServiceServer) QueryTopParksByTemp(context.Context, *QueryTopParksByTempRequest) (*QueryTopParksByTempResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryTopParksByTemp not implemented")
}
func (UnimplementedXmlServiceServer) QueryDailyStateSummary(context.Context, *QueryDailyStateSummaryRequest) (*QueryDailyStateSummaryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryDailyStateSummary not implemented")
}
func (UnimplementedXmlServiceServer) mustEmbedUnimplementedXmlServiceServer() {}
func (UnimplementedXmlServiceServer) testEmbeddedByValue()                    {}

// UnsafeXmlServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to XmlServiceServer will
// result in compilation errors.
type UnsafeXmlServiceServer interface {
	mustEmbedUnimplementedXmlServiceServer()
}

func RegisterXmlServiceServer(s grpc.ServiceRegistrar, srv XmlServiceServer) {
	// If the following call panics, it indicates UnimplementedXmlServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&XmlService_ServiceDesc, srv)
}

func _XmlService_GetDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XmlServiceServer).GetDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: XmlService_GetDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XmlServiceServer).GetDocument(ctx, req.(*GetDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _XmlService_QueryParkStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParkStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XmlServiceServer).QueryParkStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: XmlService_QueryParkStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XmlServiceServer).QueryParkStats(ctx, req.(*QueryParkStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _XmlService_QueryTopParksByTemp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryTopParksByTempRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XmlServiceServer).QueryTopParksByTemp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: XmlService_QueryTopParksByTemp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XmlServiceServer).QueryTopParksByTemp(ctx, req.(*QueryTopParksByTempRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _XmlService_QueryDailyStateSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryDailyStateSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XmlServiceServer).QueryDailyStateSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: XmlService_QueryDailyStateSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XmlServiceServer).QueryDailyStateSummary(ctx, req.(*QueryDailyStateSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// XmlService_ServiceDesc is the grpc.ServiceDesc for XmlService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var XmlService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xmlservice.XmlService",
	HandlerType: (*XmlServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDocument",
			Handler:    _XmlService_GetDocument_Handler,
		},
		{
			MethodName: "QueryParkStats",
			Handler:    _XmlService_QueryParkStats_Handler,
		},
		{
			MethodName: "QueryTopParksByTemp",
			Handler:    _XmlService_QueryTopParksByTemp_Handler,
		},
		{
			MethodName: "QueryDailyStateSummary",
			Handler:    _XmlService_QueryDailyStateSummary_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/xmlservice.proto",
}
