// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: proto/xmlservice.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	XmlService_GetDocument_FullMethodName        = "/xmlservice.XmlService/GetDocument"
	XmlService_QueryCurrentPrice_FullMethodName  = "/xmlservice.XmlService/QueryCurrentPrice"
	XmlService_QueryIncidentStats_FullMethodName = "/xmlservice.XmlService/QueryIncidentStats"
)

// XmlServiceClient is the client API for XmlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type XmlServiceClient interface {
	GetDocument(ctx context.Context, in *GetDocumentRequest, opts ...grpc.CallOption) (*GetDocumentResponse, error)
	QueryCurrentPrice(ctx context.Context, in *QueryCurrentPriceRequest, opts ...grpc.CallOption) (*QueryCurrentPriceResponse, error)
	QueryIncidentStats(ctx context.Context, in *QueryIncidentStatsRequest, opts ...grpc.CallOption) (*QueryIncidentStatsResponse, error)
}

type xmlServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewXmlServiceClient(cc grpc.ClientConnInterface) XmlServiceClient {
	return &xmlServiceClient{cc}
}

func (c *xmlServiceClient) GetDocument(ctx context.Context, in *GetDocumentRequest, opts ...grpc.CallOption) (*GetDocumentResponse, error) {
	out := new(GetDocumentResponse)
	err := c.cc.Invoke(ctx, XmlService_GetDocument_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xmlServiceClient) QueryCurrentPrice(ctx context.Context, in *QueryCurrentPriceRequest, opts ...grpc.CallOption) (*QueryCurrentPriceResponse, error) {
	out := new(QueryCurrentPriceResponse)
	err := c.cc.Invoke(ctx, XmlService_QueryCurrentPrice_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xmlServiceClient) QueryIncidentStats(ctx context.Context, in *QueryIncidentStatsRequest, opts ...grpc.CallOption) (*QueryIncidentStatsResponse, error) {
	out := new(QueryIncidentStatsResponse)
	err := c.cc.Invoke(ctx, XmlService_QueryIncidentStats_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// XmlServiceServer is the server API for XmlService service.
// All implementations must embed UnimplementedXmlServiceServer
// for forward compatibility
type XmlServiceServer interface {
	GetDocument(context.Context, *GetDocumentRequest) (*GetDocumentResponse, error)
	QueryCurrentPrice(context.Context, *QueryCurrentPriceRequest) (*QueryCurrentPriceResponse, error)
	QueryIncidentStats(context.Context, *QueryIncidentStatsRequest) (*QueryIncidentStatsResponse, error)
	mustEmbedUnimplementedXmlServiceServer()
}

// UnimplementedXmlServiceServer must be embedded to have forward compatible implementations.
type UnimplementedXmlServiceServer struct {
}

func (UnimplementedXmlServiceServer) GetDocument(context.Context, *GetDocumentRequest) (*GetDocumentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDocument not implemented")
}
func (UnimplementedXmlServiceServer) QueryCurrentPrice(context.Context, *QueryCurrentPriceRequest) (*QueryCurrentPriceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryCurrentPrice not implemented")
}
func (UnimplementedXmlServiceServer) QueryIncidentStats(context.Context, *QueryIncidentStatsRequest) (*QueryIncidentStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryIncidentStats not implemented")
}
func (UnimplementedXmlServiceServer) mustEmbedUnimplementedXmlServiceServer() {}

// UnsafeXmlServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to XmlServiceServer will
// result in compilation errors.
type UnsafeXmlServiceServer interface {
	mustEmbedUnimplementedXmlServiceServer()
}

func RegisterXmlServiceServer(s grpc.ServiceRegistrar, srv XmlServiceServer) {
	s.RegisterService(&XmlService_ServiceDesc, srv)
}

func _XmlService_GetDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XmlServiceServer).GetDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: XmlService_GetDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XmlServiceServer).GetDocument(ctx, req.(*GetDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _XmlService_QueryCurrentPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryCurrentPriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XmlServiceServer).QueryCurrentPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: XmlService_QueryCurrentPrice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XmlServiceServer).QueryCurrentPrice(ctx, req.(*QueryCurrentPriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _XmlService_QueryIncidentStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryIncidentStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XmlServiceServer).QueryIncidentStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: XmlService_QueryIncidentStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XmlServiceServer).QueryIncidentStats(ctx, req.(*QueryIncidentStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// XmlService_ServiceDesc is the grpc.ServiceDesc for XmlService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var XmlService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xmlservice.XmlService",
	HandlerType: (*XmlServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDocument",
			Handler:    _XmlService_GetDocument_Handler,
		},
		{
			MethodName: "QueryCurrentPrice",
			Handler:    _XmlService_QueryCurrentPrice_Handler,
		},
		{
			MethodName: "QueryIncidentStats",
			Handler:    _XmlService_QueryIncidentStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/xmlservice.proto",
}
